SCIeL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.invernaderos.urls', 'invernaderos'), namespace='invernaderos')),
]

apps/invernaderos/urls.py
from django.urls import path
from apps.invernaderos.views import CultivosShow
from . import views

urlpatterns = [
    path('', views.InvernaderosListView.as_view(), name='index'),
    path('invernaderos/', views.index, name='invernaderos'),
    path('perfil/<slug:pk>/', views.PerfilDetailView.as_view(), name='perfil'),
    path('sign-in/', views.SignInView.as_view(), name='sign-in'),
    path('sign-out/', views.SignOutView.as_view(), name='sign-out'),
    path('cultivos/', CultivosShow.as_view(), name='cultivos'),
    path('ajax/borrar/invernadero/', views.borrar_invernadero, name='ajax-borrar-invernadero')
]

apps/invernaderos/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.dispatch import receiver


class Cultivo(models.Model):
    id_cultivo = models.AutoField(
        primary_key=True,
        verbose_name='Codigo del cultivo',
        help_text='Identificador genérico del cultivo',
        error_messages={
            'exist': 'El indentificador ya existe'
        }
    )
    nombre_cultivo = models.CharField(
        max_length=45,
        null=True, 
        blank=True,
        verbose_name='Nombre del cultivo',
        help_text='Nombre de la planta a cultivar',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        }
    )
    periodo_cosecha = models.IntegerField(
        verbose_name='Periódo de Cosecha',
        help_text="Debe ingresar el tiempo que tarda el cultivo en dar frutos",
        error_messages={
            'value':'Debe ser un dato entero positivo'
        },
        validators=[
            MinValueValidator(0),
            MaxValueValidator(1000)
        ],
        null=True, 
        blank=True,
    )

    def __str__(self):
        return self.nombre_cultivo

    class Meta:
        ordering = ['nombre_cultivo']
        verbose_name = 'Cultivo'
        verbose_name_plural = 'Cultivos'


class Etapa(models.Model):
    id_etapa = models.AutoField(
        primary_key=True,
        verbose_name='Codigo de la etapa',
        help_text='Identificador genérico de la Etapa',
        error_messages={
            'exist': 'El indentificador ya existe',
        }
    )
    id_cultivo = models.ForeignKey(
        Cultivo,
        on_delete=models.CASCADE,
        verbose_name='Cultivo',
        help_text='Cultivo al que pertenece esta etapa',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
        null=True, 
        blank=True
    )
    numero_etapa = models.IntegerField(
        verbose_name='Número de etapa',
        null=True, 
        blank=True,
        help_text="Debe ingresar la cantidad de etapas durante el tiempo de vida del cultivo",
        error_messages={
            'value':'Debe ser un dato entero positivo'
        },
        validators=[
            MinValueValidator(0),
            MaxValueValidator(10)
        ]
    )
    nombre_etapa = models.CharField(
        max_length=45,
        verbose_name='Nombre de etapa',
        help_text='Ingrese el nombre de la etapa. Ejemplo: Floración',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )
    duracion = models.IntegerField(
        verbose_name='Duración de la etapa',
        null=True, 
        blank=True,
        help_text="Debe ingresar el tiempo que dura esta etapa",
        error_messages={
            'value':'Debe ser un dato entero positivo'
        },
        validators=[
            MinValueValidator(0)
        ]
    )
    descripcion_etapa = models.CharField(
        max_length=150,
        verbose_name='Descripcion de la etapa',
        help_text='Ingrese una breve descripción de la etapa',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )

    def __str__(self):
        return self.nombre_etapa

    class Meta:
        ordering = ["id_cultivo", "numero_etapa"]
        verbose_name = "Etapa"
        verbose_name_plural = "Etapas"


class Dispositivo(models.Model):
    id_dispositivo = models.AutoField(
        primary_key=True,
        verbose_name='Codigo del dispositivo',
        help_text='Identificador genérico del dispositivo',
        error_messages={
            'exist': 'El indentificador ya existe'
        }
    )
    nombre_dispositivo = models.CharField(
        max_length=45,
        verbose_name='Nombre del dispositivo',
        help_text='Dele un nombre al dispositivo a usar en sus invernaderos',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )

    def __str__(self):
        return self.nombre_dispositivo

    class Meta:
        ordering = ["id_dispositivo"]
        verbose_name = "Dispositivo"
        verbose_name_plural = "Dispositivos"


class Invernadero(models.Model):
    id_invernadero = models.AutoField(
        primary_key=True,
        verbose_name='Codigo del invernadero',
        help_text='Identificador genérico del invernadero',
        error_messages={
            'exist': 'El indentificador ya existe'
        }
    )
    id_dispositivo = models.ForeignKey(
        Dispositivo,
        on_delete=models.DO_NOTHING,
        verbose_name='Dispositivo',
        help_text='Dispositivo que controla este invernadero',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
        null=True, 
        blank=True
    )
    id_usuario = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name='Usuario',
        help_text='Usuario al que pertenece este invernadero',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
        null=True, 
        blank=True
    )
    id_cultivo = models.ManyToManyField(
        Cultivo,
        verbose_name='Cultivo',
        help_text='Cultivo que se cosechará en este invernadero',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
    )
    nombre_invernadero = models.CharField(
        max_length=45,
        verbose_name='Nombre del invernadero',
        help_text='Asignele un nombre cualquiera al invernadero',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )
    ubicacion = models.CharField(
        max_length=23,
        verbose_name='Ubicacion del invernadero',
        help_text='Ingrese la ubicación del invernadero',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )

    def __str__(self):
        return self.nombre_invernadero

    class Meta:
        ordering = ["id_invernadero", "nombre_invernadero"]
        verbose_name = "Invernadero"
        verbose_name_plural = "Invernaderos"


class Parametro(models.Model):
    id_parametro = models.AutoField(
        primary_key=True,
        verbose_name='Codigo del parámetro',
        help_text='Identificador genérico del parámetro que servirá de estándar',
        error_messages={
            'exist': 'El indentificador ya existe'
        }
    )
    id_invernadero = models.ForeignKey(
        Invernadero,
        on_delete=models.CASCADE,
        verbose_name='Invernadero',
        help_text='Invernadero al que se asignará este parámetro',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
        null=True, 
        blank=True
    )
    nombre_parametro = models.CharField(
        max_length=45,
        verbose_name='Nombre del parámetro',
        help_text='Ingrese el nombre del parámetro a medir',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )
    magnitud_referencia = models.DecimalField(
        verbose_name='Magnitud del Parámetro Base',
        max_digits=10,
        decimal_places=2,
        help_text='Ingrese el valor de la magnitud de referencia para este parámetro',
        error_messages={
            'value': 'Ese valor debe ser positivo'
        },
        validators=[
            MinValueValidator(0)
        ],
        null=True, 
        blank=True
    )

    def __str__(self):
        return self.nombre_parametro

    class Meta:
        ordering = ["id_invernadero","nombre_parametro"]
        verbose_name = "Parámetro"
        verbose_name_plural = "Parámetros"


class Actuador(models.Model):
    id_actuador = models.AutoField(
        primary_key=True,
        verbose_name='Codigo del Actuador',
        help_text='Identificador genérico del actuador',
        error_messages={
            'exist': 'El indentificador ya existe'
        }
    )
    id_dispositivo = models.ForeignKey(
        Dispositivo,
        on_delete=models.CASCADE,
        verbose_name='Dispositivo',
        help_text='Dispositivo que se asociará a este actuador',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
        null=True, 
        blank=True
    )
    id_invernadero = models.ForeignKey(
        Invernadero,
        on_delete=models.CASCADE,
        verbose_name='Invernadero',
        help_text='Invernadero al que se asignará este parámetro',
        error_messages={
            'select': 'Debe seleccionar uno de la lista'
        },
        null=True, 
        blank=True
    )
    nombre_actuador = models.CharField(
        max_length=45,
        verbose_name='Nombre del Actuador',
        help_text='Ingrese el nombre del actuador a usar',
        error_messages={
            'empty': 'Este campo no debe quedar vacío'
        },
        null=True, 
        blank=True
    )

    def __str___(self):
        return self.nombre_actuador

    class Meta:
        ordering = ["id_dispositivo","nombre_actuador"]
        verbose_name = "Actuador"
        verbose_name_plural = "Actuadores"


class Sensor(models.Model):
    id_sensor = models.AutoField(
        primary_key=True,

apps/invernaderos/forms.py
from .models import * 

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView


class LoginForm(AuthenticationForm):
    username =  forms.CharField(
        max_length=20,
        required=True
    )
    
    first_name = forms.CharField(
        max_length=50,
        required=True
    )
    last_name = forms.CharField(
        max_length=50,
        required=True
    )
    email = forms.EmailField(
        required=True
    )
    

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
            'error_messages'
        )


class UserUpdate(UpdateView):
    model = User
    fields = (
            'username',
            'email',
            'first_name',
            'last_name',
    )
    template_name_suffix = '_update_form'
    

class InvernaderoForm(forms.ModelForm):

    class Meta:
        model = Invernadero
        fields = (
            'id_invernadero',
            'id_dispositivo',
            'id_usuario',
            'id_cultivo',
            'nombre_invernadero',
            'ubicacion'
            )

apps/invernaderos/views.py
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect
from django.forms.models import model_to_dict
from django.urls import reverse_lazy
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.utils import timezone

from django.views.generic import CreateView, TemplateView 

from .forms import LoginForm, UserUpdate
from .models import *

import json

class SignUpView(LoginRequiredMixin, CreateView):
    model = User
    form_class = LoginForm


class SignInView(LoginView):
    template_name = 'invernaderos/iniciarSesion.html'

    
"""class Login(FormView):
    form_class = AuthenticationForm
    template_name = 'invernaderos/iniciarSesion.html'
    success_url = reverse_lazy('invernaderos:invernaderos')
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(self, Login).dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(self, Login).form_valid(form)
"""

class SignOutView(LoginRequiredMixin, LogoutView):
    template_name = 'invernaderos/iniciarSesion.html'


class PerfilDetailView(LoginRequiredMixin, DetailView):
    template_name = 'invernaderos/editarPerfil.html'
    model = User
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super(PerfilDetailView, self).get_conno rtext_data(**kwargs)
        return context


class InvernaderosListView(LoginRequiredMixin, ListView):
    model = Invernadero
    template_name = 'invernaderos/gestionarInvernaderos.html'
    context_object_name = 'invernaderos'


    def get_queryset(self):
        context = Invernadero.objects.all()
        return context
    
    def get_context_data(self, **kwargs):
        context = super(InvernaderosListView, self).get_context_data(**kwargs)
        return context

class InicioView(LoginRequiredMixin, TemplateView):
    template_name = 'invernaderos/gestionarInvernaderos.html'


class CultivosShow(TemplateView):
    template_name = 'invernaderos/gestionarCultivos.html'
    

"""def invernadero_ajax(request):
    id_invernadero = request.POST['id_invernadero']
    invernadero = Invernadero.objects.filter(id_invernadero=id_invernadero)
    dispositivo = Dispositivo.objects.filter(id_dispositivo=invernadero.id_dispositivo)
    sensores = Sensores.objects.filter(id_dispositivo=dispositivo.id_dispositivo).order_by('nombre_dispositivo')
    objetos = []
    lista_sensores = []
    if request.POST['action'] == 'ver' or request.POST['action'] == 'editar':
        for sensor in sensores:
            lista_sensores.append({
                'id_sensor': sensor.id_sensor,
                'nombre_sensor': sensor.nombre_sensor
            })
        objetos.append({
            'id_invernadero': invernadero.id_invernadero,
            'nombre_invernadero': invernadero.nombre_invernadero,
            'ubicacion': invernadero.ubicacion,
            'id_dispositivo': dispositivo.id_dispositivo,
            'nombre_dispositivo': dispositivo.nombre_dispositivo,
            'lista_sensores': lista_sensores
        })
    elif request.POST['action'] == 'borrar':
        objetos.append({
            'id_invernadero': invernadero.id_invernadero,
            'nombre_invernadero': invernadero.nombre_invernadero
        })
    return HttpResponse(json.dumps(objetos), content_type='application/json')"""

def borrar_invernadero(request):
    if request.method == 'POST':
        id_invernadero = request.GET.get('id_invernadero')
        result = Invernadero.objects.filter(id_invernadero=id_invernadero).delete()
        if result == True:
            message = "El invernadero fue borrado exitosamente"
        else:
            message = "El invernadero no pudo ser borrado"
        data = {
        'message': message
        }
        return JsonResponse(data)


templates/invernaderos/editarPerfil.html
{% extends "header&footer.html" %}
{% block title %}SCIeL | Perfil{% endblock%}
{% block content %}
    <!--
        <form method="POST" class="form-group form-control">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" href="{% url 'invernaderos:sign-in' %}" name="submit" type="submit">Guardar Cambios</button>
        </form>
    -->
    
{% endblock content %}

templates/invernaderos/gestionarActuadores.html
{% extends 'header&footer.html' %}
{% block title %}SCIeL - Gestión de Actuadores{% endblock title %}

{% block content %}

  {% block sidebar %}
    {% if user.is_authenticated %}
      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'invernaderos:dispositivos' %}">
            <i class="fas fa-fw fa-cubes"></i>
            <span>Dispositivos</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'invernaderos:sensores' %}">
            <i class="fas fa-fw fa-thermometer-quarter"></i>
            <span>Sensores</span>
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'invernaderos:actuadores' %}">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Actuadores</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'invernaderos:invernaderos' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Invernaderos</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'invernaderos:cultivos' %}">
            <i class="fas fa-fw fa-leaf"></i>
            <span>Cultivos</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'invernaderos:parametros' %}">
            <i class="fas fa-fw fa-cogs"></i>
            <span>Parámetros Estándar</span>
          </a>
        </li>
      </ul>
    {% endif %}
  {% endblock sidebar %}
  {% block tables %}
    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="#">Actuador</a>
          </li>
          <li class="breadcrumb-item active">Datos</li>
        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Actuador
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="text-center">
                  <tr>
                    <th>Nombre del Actuador</th>
                    <th>Dispositivo</th>
                    <th>Invernadero</th>
                    <th>Operaciones</th>
                  </tr>
                </thead>
                <tbody id="bodyTable">
                  {% for actuador in actuadores %}    
                    <tr id="{{actuador.id_actuador}}">
                      <td>{{ actuador.nombre_actuador }}</td>
                      <td>{{ actuador.id_dispositivo }}</td>
                      <td>{{ actuador.id_invernadero }}</td>
                      <td class="text-center">
                        {% csrf_token %}
                        <a class="fas fa-w fa-eye" name="ver" href="#"  data-toggle="modal" onclick="operacion({{ actuador.id_actuador }}, '{{actuador.nombre_actuador}}', '/ajax/actuador/', 'GET', 'ACTUADOR');" style="color:gray !important"></a>
                        <a class="fas fa-w fa-edit" name="editar" href="#" data-toggle="modal" onclick="operacion({{ actuador.id_actuador }}, '{{actuador.nombre_actuador}}', '/ajax/actuador/', 'LOAD', 'ACTUADOR');" style="color:gray !important"></a>
                        <a class="fas fa-w fa fa-trash" name="eliminar" href="#" data-toggle="modal" onclick="operacion({{ actuador.id_actuador }}, '{{actuador.nombre_actuador}}', '/ajax/actuador/', 'DELETE', 'ACTUADOR');" style="color:gray !important"></a>
                      </td>                          
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  {% endblock tables %}
    
{% endblock content %}

templates/invernaderos/gestionarCultivos.html
{% extends 'header&footer.html' %}
{% block title %}SCIeL | Gestión de Cultivos{% endblock title %}

{% block content %}
  
      <div id="wrapper">
        {% block sidebar %}
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'invernaderos:sign-in' %}">
              <!--<i class="fas fa-fw fa-tachometer-alt"></i>-->
              <span>Monitoreo</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'invernaderos:sign-in' %}">
              <!--<i class="fas fa-fw fa-chart-area"></i>-->
              <span>Invernaderos</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'invernaderos:cultivos' %}">
              <!--<i class="fas fa-fw fa-table"></i>-->
              <span>Cultivos</span></a>
          </li>
        </ul>
        {% endblock sidebar %}

        <div id="content-wrapper">

          <div class="container-fluid">

            <!-- Breadcrumbs-->
            <!--<ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="#">Dashboard</a>
              </li>
              <li class="breadcrumb-item active">Tables</li>
            </ol>-->

            <!-- DataTables Example -->
            <div class="card mb-3">
              <div class="card-header">
                <i class="fas fa-table"></i>
                INFORMACIÓN DE CULTIVOS</div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                      <tr class="text-center">
                        <th>ID</th>
                        <th>Nombre de Cultivo</th>
                        <th>Período de Cosecha</th>
                        <th>Número de Etapas</th>
                        <th>Temperatura</th>
                        <th>Humedad</th>
                        <th>Humedad Relativa</th>
                        <th>Intensidad de Luz</th>
                        <th>Acciones</th>
                      </tr>
                    </thead>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
            </div>
            <button class="btn btn-lg btn-primary btn-lg" style="width:200px; height:50px" href="#ventanaCultivo" data-toggle="modal">Agregar Cultivo
            </button>
            <div class="modal fade" id="ventanaCultivo">
              <div class="modal-dialog">
                <div class="modal-content">
                  <!--Header ventana-->
                  <div class="modal-header">
                    <div class ="modal-title"><b>INFORMACIÓN DEL CULTIVO</b></div>
                  </div>
                  <!--Body ventana-->
                  <div class="modal-body">
                    <label for="nombre">Nombre:</label>
                    <input class="form-control" id="nombre" type="text" placeholder="Ingrese el nombre del cultivo">
                    <label for="periodoCosecha">Período de Cosecha:</label>
                    <input class="form-control" id="periodoCosecha" type="text" placeholder="Ingrese el período de cosecha en días">
                    <label for="numeroEtapas">Número de Etapas:</label>
                    <input class="form-control" id="numeroEtapas" type="text" placeholder="Ingrese número de etapas del cultivo">
                    <label for="temperaturaBase">Temperatura(°C):</label>
                    <input class="form-control" id="temperaturaBase" type="text" placeholder="Ingrese la temperatura estándar">
                    <label for="humBase">Humedad(%):</label>
                    <input class="form-control" id="humBase" type="text" placeholder="Ingrese la humedad estándar">
                    <label for="humRelBase">Humedad Relativa(%):</label>
                    <input class="form-control" id="humRelBase" type="text" placeholder="Ingrese la humedad relativa estándar">
                    <label for="intLuzBase">Intensidad de Luz(candela:cd):</label>
                    <input class="form-control" id="intLuzBase" type="text" placeholder="Ingrese la intensidad de luz estándar">

                  </div>
                  <!--Footer ventana-->
                  <div class="modal-footer">             
                    <button type="button" class="btn btn-primary" href="{% url 'invernaderos:cultivos' %}">Guardar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                  </div>
                </div>
              </div>
            </div>
            <!--<p class="small text-center text-muted my-5">
              <em>More table examples coming soon...</em>
            </p>-->

          </div>
          <!-- /.container-fluid -->

          <!-- Sticky Footer -->
          <footer class="sticky-footer">
            <div class="container my-auto">
              <div class="copyright text-center my-auto">
                <span>Copyright © SCIeL 2018 | Sistema para el Control de Invernaderos en Línea</span>
              </div>
            </div>
          </footer>

        </div>
        <!-- /.content-wrapper -->

      </div>
      <!-- /#wrapper -->

      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>

      <!-- Logout Modal-->
      <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">¿Seguro que quieres cerrar la sesión?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">Seleccione "Cerrar sesión" a continuación si está listo para finalizar su sesión actual</div>
            <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
            <a class="btn btn-primary" href="login.html">Cerrar Sesión</a>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

templates/invernaderos/iniciarSesion.html
{% extends "header&footer.html" %}
{% block title %}SCIeL | Iniciar Sesión{% endblock %}
{% block content %}
  {% load static from staticfiles  %}
  <header class="py-2 bg-image-full mx-auto" style="background-image: url('/static/media/image/CE - UES 3.JPG'); background-size: cover;">
    <div>
      <div class="card card-login mx-auto bg-dark view overlay">
        <div class="card-header text-center" style="color:whitesmoke !important;">
          <h3 class="h5">
            <img class="img-fluid d-block mx-auto mb-4" src="{% static 'media/image/logo2.png' %}" alt="" width="250" height="250" style="padding-top: 0.5rem; padding-bottom: 0.3rem;">
            Sistema para el Control de Invernaderos en Línea - SCIeL
          </h3>
          {% if form.message %}
          <div class="alert alert-danger in alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>  
              <p>{{form.message}}</p>
            </strong>
          </div>
        {% endif %}
      </div>
      <div class="card-body form-group form-label-group text-center">
        <strong>
          <form method="POST" class="form-signup">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_username" style="color:lightgray !important;">
                Nombre de usuario
              </label>
              {{ form.username }}
            </div>
            <div class="form-group">
              <label for="id_password" style="color:lightgray !important;">
                Contraseña
              </label>
              {{ form.password }}
            </div>
            <button class="btn btn-lg btn-primary btn-block" href="{% url 'invernaderos:invernaderos' %}" name="submit" type="submit">Iniciar Sesión</button>
          </form>
        </strong>
      </div>
    </div>      
  </header>
{% endblock content %}
{% block footer %}
<footer class="py-5 bg-dark" style="background-color: #343a40!important;">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; SCIeL 2018 | Sistema para el Control de Invernaderos en Línea</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock footer %}