SCIeL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.invernaderos.urls', 'invernaderos'), namespace='invernaderos')),
]

apps/invernaderos/urls.py
from django.urls import path
from apps.invernaderos.views import CultivosShow
from . import views

urlpatterns = [
    path('', views.InvernaderosListView.as_view(), name='index'),
    path('invernaderos/', views.index, name='invernaderos'),
    path('perfil/<slug:pk>/', views.PerfilDetailView.as_view(), name='perfil'),
    path('sign-in/', views.SignInView.as_view(), name='sign-in'),
    path('sign-out/', views.SignOutView.as_view(), name='sign-out'),
    path('cultivos/', CultivosShow.as_view(), name='cultivos'),
    path('ajax/borrar/invernadero/', views.borrar_invernadero, name='ajax-borrar-invernadero')
]

templates/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
        
    <title>{% block title %}{% endblock %}</title>
    
    {% load staticfiles %}    
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'media/image/favicon2.ico' %}">
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        
    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css">
        
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="page-top">
        {% block header %}
        {% endblock header %}
        {% block content %}
            {% block sidebar %}
            {% endblock sidebar %}
            {% block tables %}
            {% endblock tables %}
            {% block modals %}
            {% endblock modals %}
        {% endblock content %}
        {% block footer %}
        {% endblock footer %}
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">¿Seguro que quieres cerrar la sesión?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Seleccione "Cerrar sesión" a continuación si está listo para finalizar su sesión actual</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                            <a class="btn btn-primary" href="{% url 'invernaderos:sign-out' %}">Cerrar Sesión</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

        <!-- Page level plugin JavaScript-->
        <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
        <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin.min.js' %}"></script>
        <script src="{% static 'js/invernaderos.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>

        <!-- Demo scripts for this page-->
        <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    </div>
</body>
</html>

templates/header&footer.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block header %}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
          <i>
            {% load staticfiles %}
            <img class="image-circle" style="max-width:120px; margin-top: -7px;" src="{% static 'media/image/logo2.png' %}">
          </i>
        </button>

        {% if user.is_authenticated %}
          <!-- Navbar Search -->
          <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </form>
  
          <!-- Navbar -->
          <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.first_name %}
                  <i>{{ user.first_name }} {{ user.last_name }} <span class="fas fa-user-circle fa-fw"></span></i>
                {% else %}
                  <i>{{ user.username }} <span class="fas fa-user-circle fa-fw"></span></i>
                {% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="perfil/{{user.id}}">Perfil</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Salir</a>
              </div>
            </li>
        </ul>
        {% endif %}
      </nav>
{% endblock header%}
{% block content %}
{% endblock content %}